config/routes.rb
RailsOmni::Application.routes.draw do
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  resources :police
  resources :precincts
  resources :titles
  resources :departments

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/precinct.rb
module FindOrCreateByNameExtension
  def find_or_create_by_name(name)
    find_or_create_by(name: name)
  end
end

class Precinct < ActiveRecord::Base
  has_many :police, inverse_of: :police, extend: FindOrCreateByNameExtension
  validates :name, presence: true, uniqueness: true
end

app/controllers/precincts_controller.rb
class PrecinctsController < ApplicationController
  before_action :set_precinct, only: [:show, :edit, :update, :destroy]

  # GET /precincts
  # GET /precincts.json
  def index
    @precincts = Precinct.all
  end

  # GET /precincts/1
  # GET /precincts/1.json
  def show
  end

  # GET /precincts/new
  def new
    @precinct = Precinct.new
  end

  # GET /precincts/1/edit
  def edit
  end

  # POST /precincts
  # POST /precincts.json
  def create
    @precinct = Precinct.new(precinct_params)

    respond_to do |format|
      if @precinct.save
        format.html { redirect_to @precinct, notice: 'Precinct was successfully created.' }
        format.json { render action: 'show', status: :created, location: @precinct }
      else
        format.html { render action: 'new' }
        format.json { render json: @precinct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /precincts/1
  # PATCH/PUT /precincts/1.json
  def update
    respond_to do |format|
      if @precinct.update(precinct_params)
        format.html { redirect_to @precinct, notice: 'Precinct was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @precinct }
      else
        format.html { render action: 'edit' }
        format.json { render json: @precinct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /precincts/1
  # DELETE /precincts/1.json
  def destroy
    @precinct.destroy
    respond_to do |format|
      format.html { redirect_to precincts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_precinct
      @precinct = Precinct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def precinct_params
      params.require(:precinct).permit(:name)
    end
end

app/helpers/precincts_helper.rb
module PrecinctsHelper
end

app/views/precincts/_form.html.haml
= simple_form_for(@precinct) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/precincts/edit.html.haml
%h1 Editing precinct

= render 'form'

= link_to 'Show', @precinct
\|
= link_to 'Back', precincts_path

app/views/precincts/index.html.haml
%h1 Listing precincts

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @precincts.each do |precinct|
    %tr
      %td= precinct.name
      %td= link_to 'Show', precinct
      %td= link_to 'Edit', edit_precinct_path(precinct)
      %td= link_to 'Destroy', precinct, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Precinct', new_precinct_path

app/views/precincts/new.html.haml
%h1 New precinct

= render 'form'

= link_to 'Back', precincts_path

app/views/precincts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @precinct.name

= link_to 'Edit', edit_precinct_path(@precinct)
\|
= link_to 'Back', precincts_path