config/routes.rb
RailsOmni::Application.routes.draw do
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  resources :police
  resources :precincts
  resources :titles
  resources :departments

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/police.rb
require 'csv'

class Police < ActiveRecord::Base
  belongs_to :department, inverse_of: :police
  belongs_to :precinct, inverse_of: :police
  belongs_to :title, inverse_of: :police

  validates_associated :department
  #validates_associated :precinct
  validates_associated :title

  accepts_nested_attributes_for :department, :precinct, :title

  def self.import(path)
    deps = [:department, :title, :precinct]
    CSV.foreach(path, {headers: true, return_headers: false}) do |row|
      attrs = HashWithIndifferentAccess.new(row.to_h)
      dname, tname, pname = *attrs.values_at(*deps)
      police = Police.new(attrs.except(*deps))
      police.department = Department.find_or_create_by(name: dname) unless dname.nil?
      police.title = Title.find_or_create_by(name: tname) unless tname.nil?
      police.precinct = Precinct.find_or_create_by(name: pname) unless pname.nil?
      police.save!
    end
  end
end

app/controllers/police_controller.rb
class PoliceController < ApplicationController
  before_action :set_police, only: [:show, :edit, :update, :destroy]

  # GET /police
  # GET /police.json
  def index
    @police = Police.all
  end

  # GET /police/1
  # GET /police/1.json
  def show
  end

  # GET /police/new
  def new
    @police = Police.new
  end

  # GET /police/1/edit
  def edit
  end

  # POST /police
  # POST /police.json
  def create
    @police = Police.new(police_params)

    respond_to do |format|
      if @police.save
        format.html { redirect_to @police, notice: 'Police was successfully created.' }
        format.json { render action: 'show', status: :created, location: @police }
      else
        format.html { render action: 'new' }
        format.json { render json: @police.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /police/1
  # PATCH/PUT /police/1.json
  def update
    respond_to do |format|
      if @police.update(police_params)
        format.html { redirect_to @police, notice: 'Police was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @police }
      else
        format.html { render action: 'edit' }
        format.json { render json: @police.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /police/1
  # DELETE /police/1.json
  def destroy
    @police.destroy
    respond_to do |format|
      format.html { redirect_to police_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_police
      @police = Police.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def police_params
      params.require(:police).permit(:first_name, :last_name, :svcid_badge, :year_verified, :title_id, :department_id, :precinct_id)
    end
end

app/helpers/police_helper.rb
module PoliceHelper
end

app/views/police/_form.html.haml
= simple_form_for(@police) do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :last_name
    = f.input :svcid_badge
    = f.input :year_verified
    = f.association :title,      include_blank: true
    = f.association :department, include_blank: true
    = f.association :precinct,   include_blank: true

  .form-actions
    = f.button :submit

app/views/police/edit.html.haml
%h1 Editing Police

= render 'form'

= link_to 'Show', @police
\|
= link_to 'Back', police_index_path

app/views/police/index.html.haml
%h1 Listing Police

%table.table.table-striped.table-condensed.table-bordered.bootstrap-datatable.datatable
  %tr
    %th.text-center First Name
    %th.text-center Last Name
    %th.text-center SvcId / Badge#
    %th.text-center Year Verified
    %th.text-center Title
    %th.text-center Department
    %th.text-center Precinct
    %th
    %th
    %th

  - @police.each do |police|
    %tr
      %td= police.first_name
      %td= police.last_name
      %td= police.svcid_badge
      %td= police.year_verified
      %td= police.title.name
      %td= police.department.name
      %td.text-center= police.precinct.nil? ? '   -    ' : police.precinct.name
      %td= link_to 'Show', police
      %td= link_to 'Edit', edit_police_path(police)
      %td= link_to 'Destroy', police, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Police', new_police_path

app/views/police/new.html.haml
%h1 New Police

= render 'form'

= link_to 'Back', police_index_path

app/views/police/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @police.first_name
%p
  %b Last name:
  = @police.last_name
%p
  %b Svcid badge:
  = @police.svcid_badge
%p
  %b Year verified:
  = @police.year_verified
%p
  %b Title:
  = @police.title.name
%p
  %b Department:
  = @police.department.name
%p
  %b Precinct:
  = @police.precinct.nil? ? '-' : @police.precinct.name

= link_to 'Edit', edit_police_path(@police)
\|
= link_to 'Back', police_index_path