config/routes.rb
RailsOmni::Application.routes.draw do
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  resources :police
  resources :precincts
  resources :titles
  resources :departments

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/title.rb
module FindOrCreateByNameExtension
  def find_or_create_by_name(name)
    find_or_create_by(name: name)
  end
end

class Title < ActiveRecord::Base
  has_many :police, inverse_of: :police, extend: FindOrCreateByNameExtension
  validates :name, presence: true, uniqueness: true
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  before_action :set_title, only: [:show, :edit, :update, :destroy]

  # GET /titles
  # GET /titles.json
  def index
    @titles = Title.all
  end

  # GET /titles/1
  # GET /titles/1.json
  def show
  end

  # GET /titles/new
  def new
    @title = Title.new
  end

  # GET /titles/1/edit
  def edit
  end

  # POST /titles
  # POST /titles.json
  def create
    @title = Title.new(title_params)

    respond_to do |format|
      if @title.save
        format.html { redirect_to @title, notice: 'Title was successfully created.' }
        format.json { render action: 'show', status: :created, location: @title }
      else
        format.html { render action: 'new' }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titles/1
  # PATCH/PUT /titles/1.json
  def update
    respond_to do |format|
      if @title.update(title_params)
        format.html { redirect_to @title, notice: 'Title was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @title }
      else
        format.html { render action: 'edit' }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1
  # DELETE /titles/1.json
  def destroy
    @title.destroy
    respond_to do |format|
      format.html { redirect_to titles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_title
      @title = Title.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def title_params
      params.require(:title).permit(:name)
    end
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/titles/_form.html.haml
= simple_form_for(@title) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/titles/edit.html.haml
%h1 Editing title

= render 'form'

= link_to 'Show', @title
\|
= link_to 'Back', titles_path

app/views/titles/index.html.haml
%h1 Listing Position Titles

%table.table.table-striped.table-condensed.table-bordered.bootstrap-datatable.datatable
  %tr
    %th Job Title
    %th
    %th
    %th

  - @titles.each do |title|
    %tr
      %td= title.name
      %td= link_to 'Show', title
      %td= link_to 'Edit', edit_title_path(title)
      %td= link_to 'Destroy', title, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Title', new_title_path

app/views/titles/new.html.haml
%h1 New title

= render 'form'

= link_to 'Back', titles_path

app/views/titles/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @title.name

= link_to 'Edit', edit_title_path(@title)
\|
= link_to 'Back', titles_path